name: GitHub Action Slack Notify CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js v12.x
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Notify slack
        id: slack
        uses: ./
        with:
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel_id: plat-eng-notifications
          status: STARTED
          color: warning

      - name: Notify slack success
        uses: ./
        with:
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          message_id: ${{ steps.slack.outputs.message_id }}
          channel_id: plat-eng-notifications
          status: SUCCESS
          color: good
